[build]
  cmd = "go build -o ./tmp/bastion-server ./cmd/main.go"
  bin = "./tmp/bastion-server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "keys"]
  delay = 1000

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
